[[plugins]]
repo = 'junegunn/vim-easy-align'
hook_add = '''
xmap gga :Tabular
xmap ga  <Plug>(EasyAlign)
'''
on_map = '<Plug>(EasyAlign)'

[[plugins]]
repo = 'cohama/lexima.vim'
on_event = 'InsertEnter'

[[plugins]]
repo = 'scrooloose/nerdcommenter'
hook_add = '''
let g:NERDSpaceDelims=1
let g:NERDDefaultAlign='left'
let g:NERDCustomDelimiters = {'vim': {'left': '"','right':''}}
let g:NERDCreateDefaultMappings=0
map <Leader>c<space> <plug>NERDCommenterToggle
'''
on_map = '<plug>NERDCommenterToggle'

[[plugins]]
repo='t9md/vim-quickhl.git'
hook_add = '''
nmap <leader>m <Plug>(quickhl-manual-this)
xmap <leader>m <Plug>(quickhl-manual-this)
nmap <leader>M <Plug>(quickhl-manual-reset)
xmap <leader>M <Plug>(quickhl-manual-reset)
'''
on_map = '<Plug>(quickhl-manual-this)'

[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = '''
map <leader>e <Plug>(easymotion-prefix)
'''
on_map = '<Plug>(easymotion-prefix)'

# language server ===============================

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
on_ft = ['c', 'cpp', 'rust', 'python', 'vim', 'tex', 'javascript', 'typescript', 'css', 'vue']
depends = ['vim-lsp-settings', 'vim-lsp-icons']
hook_add = '''
function! s:on_lsp_buffer_enabled() abort
  nmap <buffer> <Leader>lc  <plug>(lsp-declaration)
  nmap <buffer> <Leader>ld  <plug>(lsp-definition)
  nmap <buffer> <Leader>lh  <plug>(lsp-hover)
  nmap <buffer> <Leader>li  <plug>(lsp-implementation)
  imap <buffer> <C-s>       <plug>(lsp-signature-help)
  nmap <buffer> <Leader>lt  <plug>(lsp-type-definition)
  nmap <buffer> <Leader>lr  <plug>(lsp-rename)
  nmap <buffer> <Leader>lk  <plug>(lsp-references)
  nmap <buffer> <Leader>ls  <plug>(lsp-document-symbol)
  nmap <buffer> <Leader>lw  <plug>(lsp-workspace-symbol)
  nmap <buffer> <Leader>lf  <plug>(lsp-document-format)
  nmap <buffer> <Leader>le  <plug>(lsp-document-diagnostics)
endfunction

augroup lsp_install
    au!
    autocmd User lsp_buffer_enabled call s:on_lsp_buffer_enabled()
augroup END

let g:lsp_diagnostics_echo_cursor = 1
let g:lsp_diagnostics_enabled = 1
let g:lsp_diagnostics_signs_enabled = 0
let g:lsp_diagnostics_virtual_text_enabled = 0
let g:lsp_diagnostics_echo_delay = 50
let g:lsp_diagnostics_highlights_enabled = 0
'''

[[plugins]]
repo = 'mattn/vim-lsp-settings'
[[plugins]]
repo = 'mattn/vim-lsp-icons'

# language server ===============================

[[plugins]]
repo = 'lervag/vimtex'
# rev = 'v2.6'
on_ft = ['tex','cls']
hook_source= '''
let g:vimtex_syntax_conceal_disable=1
let g:vimtex_mappings_enabled=0
let g:vimtex_compiler_latexmk = {
    \ 'build_dir' : '',
    \ 'callback' : 1,
    \ 'continuous' : 1,
    \ 'executable' : 'latexmk',
    \}

nmap <localleader>ll  <plug>(vimtex-compile)
nmap <localleader>lt  <plug>(vimtex-toc-toggle)
nmap <localleader>ls  <plug>(vimtex-status-all)

let g:vimtex_quickfix_ignore_filters = [
      \ 'Font Warning',
      \ 'Underfull',
      \]

if g:OSTYPE == "Darwin"
  let g:vimtex_view_method = 'skim'
elseif g:OSTYPE == "Linux"
  let g:vimtex_view_general_viewer = 'evince'
endif
'''

#ここを参考https://qiita.com/alpaca_taichou/items/056a4c42fe7a928973e6

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html','htm','md','markdown', 'vue']
hook_source = '''
let g:user_emmet_leader_key=',,'
'''

[[plugins]]
repo = 'Yggdroot/indentLine'
on_ft = ['c','cpp','python','tex', 'javascript', 'rust', 'html', 'css', 'java', 'vue']
hook_source = '''
let g:indentLine_char_list = ['|', '¦']
let g:indentLine_setColors = 1
'''


[[plugins]]
repo = 'https://github.com/hail2u/vim-css3-syntax'
on_ft = ['html','htm']


[[plugins]]
repo = 'https://github.com/kchmck/vim-coffee-script'
on_ft = ['html','htm']

[[plugins]]
repo = 'https://github.com/AtsushiM/sass-compile.vim'
on_ft = ['sass','scss','css']
hook_add = '''
let g:sass_compile_auto                 = 1
let g:sass_compile_cdloop               = 5
let g:sass_compile_cssdir               = ['css', 'stylesheet']
let g:sass_compile_file                 = ['scss', 'sass']
let g:sass_started_dirs                 = []
let g:sass_compile_beforecmd            = ''
autocmd FileType less,sass  setlocal sw = 2 sts=2 ts=2 et
'''
depends = ['search-parent']

[[plugins]]
repo = 'AtsushiM/search-parent.vim'
on_ft = ['sass','scss','css']

[[plugins]]
repo = 'https://github.com/akiyan/vim-textobj-php'
on_ft = ['html','htm']

[[plugins]]
repo = 'https://github.com/tpope/vim-surround'
on_ft = ['html','htm']

[[plugins]]
repo = 'https://github.com/ap/vim-css-color'
on_ft = ['html','htm', 'vim']

[[plugins]]
repo = 'https://github.com/cakebaker/scss-syntax.vim'
on_ft = ['html','htm']


[[plugins]]
repo='maksimr/vim-jsbeautify'
on_ft=['js', 'html', 'jsx', 'json', 'css']
hook_source = '''
augroup Beautifytype
  "for javascript
  autocmd FileType javascript noremap <buffer> <leader>aj :call JsBeautify()<cr>
  " for json
  autocmd FileType json noremap <buffer> <leader>aj :call JsonBeautify()<cr>
  " for jsx
  autocmd FileType jsx noremap <buffer> <leader>aj :call JsxBeautify()<cr>
  " for html
  autocmd FileType html noremap <buffer> <leader>aj :call HtmlBeautify()<cr>
  " for css or scss
  autocmd FileType css noremap <buffer> <leader>aj :call CSSBeautify()<cr>
augroup END
'''

[[plugins]]
repo = 'plasticboy/vim-markdown.git'
on_ft = ['markdown']
hook_source = '''
let g:vim_markdown_no_default_key_mappings=1
let g:vim_markdown_new_list_item_indent=0
let g:vim_markdown_conceal=0
let g:vim_markdown_conceal_code_blocks=0
let g:vim_markdown_math=1
let g:vim_markdown_auto_insert_bullets=1
'''

[[plugins]]
repo = 'https://github.com/dense-analysis/ale'
on_ft=['markdown']
hook_source = '''
" let g:ale_sign_column_always=1
" let g:ale_lint_on_save=1
" let g:ale_lint_on_text_changed=1
" let g:ale_lint_on_enter=0
" let g:ale_open_list=0
let g:ale_completion_enabled=1

nnoremap <leader>af :ALEFix<CR>
nnoremap <leader>al :ALELint<CR>
nnoremap ]a :ALENext<CR>
nnoremap [a :ALEPrevious<CR>

let g:ale_linters={}
let g:ale_linters={
  \ 'markdown' : ['textlint'],
  \}
let g:ale_fixers = {
  \ 'markdown' : ['textlint'],
  \}
'''

[[plugins]]
repo = "rhysd/vim-grammarous"
on_ft = ["markdown", "txt"]
hook_source = '''
let g:grammarous#enable_spell_check=1
'''

[[plugins]]
repo = "kamykn/spelunker.vim"
on_ft = ["markdown", "latex"]
