[ftplugin]
python = '''
setlocal tabstop=4
setlocal shiftwidth=4
setlocal expandtab
setlocal textwidth=100
setlocal foldmethod=indent
'''

c = '''
setlocal tabstop=2
setlocal shiftwidth=2
setlocal foldmethod=syntax
setlocal expandtab
setlocal textwidth=80
nnoremap ,x <Cmd>QuickRun make/src<CR>
nnoremap ,,x <Cmd>QuickRun cmake/src<CR>
'''

cpp = '''
setlocal tabstop=2
setlocal shiftwidth=2
setlocal foldmethod=syntax
setlocal expandtab
setlocal textwidth=80
nnoremap ,x <Cmd>QuickRun make/src<CR>
nnoremap ,,x <Cmd>QuickRun cmake/src<CR>
'''

go = '''
setlocal tabstop=4
setlocal shiftwidth=4
setlocal expandtab
setlocal formatoptions+r
setlocal foldmethod=indent
'''

tex = '''
setlocal tabstop=2
setlocal shiftwidth=2
setlocal foldmethod=indent
setlocal expandtab
setlocal wrap
setlocal conceallevel=0
'''

html = '''
setlocal tabstop=2
setlocal shiftwidth=2
setlocal expandtab
setlocal nowrap
setlocal iskeyword+=-
setlocal foldmethod=indent
'''

css = '''
setlocal tabstop=2
setlocal shiftwidth=2
setlocal expandtab
setlocal nowrap
setlocal iskeyword+=-
setlocal foldmethod=indent
'''

vim = '''
setlocal tabstop=2
setlocal shiftwidth=2
setlocal expandtab
setlocal nowrap
setlocal foldmethod=indent
'''

javascript = '''
setlocal tabstop=2
setlocal shiftwidth=2
setlocal expandtab
setlocal nowrap
setlocal foldmethod=indent
'''

csv = '''
setlocal tabstop=4
setlocal shiftwidth=4
setlocal expandtab
setlocal nowrap
imap , ,
'''

text = '''
setlocal tabstop=4
setlocal shiftwidth=4
setlocal expandtab
'''

help = '''
setlocal noet
setlocal foldmethod=indent
'''

markdown = '''
setlocal tabstop=4
setlocal shiftwidth=4
setlocal expandtab
setlocal wrap
'''

vue = '''
setlocal tabstop=2
setlocal shiftwidth=2
setlocal expandtab
setlocal nowrap
setlocal iskeyword+=-
setlocal foldmethod=indent
'''
