[[plugins]]
repo = 'Shougo/ddu.vim'
depends = "denops.vim"
on_source = 'denops.vim'


#  setting script
hook_source = '''
call ddu#custom#patch_global({
  \ 'ui': 'ff',
  \ 'uiParams': {
  \   'ff':{
  \     'split':  'horizontal',
  \     'startFilter':  v:true,
  \   },
  \   'filer':{
  \     'split':  'no',
  \   },
  \ },
  \ 'sourceOptions': {
  \   '_': {
  \     'matchers': ['matcher_substring'],
  \     'ignoreCase': v:true,
  \     'path': expand("%:p:h"),
  \     'columns': ['filename'],
  \   },
  \ },
  \ 'kindOptions': {
  \   'file': {
  \     'defaultAction': 'open',
  \   },
  \   'command_history': {
  \     'defaultAction': 'execute',
  \   },
  \ },
  \ 'actionOptions': {
  \   'narrow': {'quit': v:false},
  \ },
  \ 'filterParams': {
  \   'matcher_substring': {'highlightMatched': 'Search'},
  \ },
  \ })

call ddu#custom#patch_local('filer', {
  \ 'ui': 'filer',
  \ 'sources': [{'name': 'file'}],
  \ 'uiParams': {
  \   'filer': {
  \     'split': 'no',
  \   },
  \ },
  \ })

call ddu#custom#patch_local('filer_left', {
  \ 'ui': 'filer',
  \ 'sources': [{'name': 'file'}],
  \ 'uiParams': {
  \   'filer': {
  \     'split': 'vertical',
  \     'splitDirection': 'topleft',
  \     'winWidth': 40,
  \   },
  \ },
  \ })

call ddu#custom#patch_local('filer_float', {
  \ 'ui': 'filer',
  \ 'sources': [{'name': 'file'}],
  \ 'uiParams': {
  \   'filer': {
  \     'split': 'horizontal',
  \   },
  \ },
  \ })
'''

hook_add = '''
nnoremap <silent> <space>ff  <Cmd>call ddu#start({'sources': [{'name': 'file_rec'}]})<CR>
nnoremap <silent> <space>fr  <Cmd>call ddu#start({'sources': [{'name': 'file_old'}]})<CR>
nnoremap <silent> /          <Cmd>call ddu#start({'sources': [{'name': 'line'}]})<CR>
nnoremap <silent> <space>fb  <Cmd>call ddu#start({'sources': [{'name': 'buffer'}]})<CR>
nnoremap <silent> <space>fc  <Cmd>call ddu#start({'sources': [{'name': 'command_history'}]})<CR>
nnoremap <silent> <space>d   <Cmd>call ddu#start({'name': 'filer'})<CR>
nnoremap <silent> st         <Cmd>tabnew<CR><Cmd>call ddu#start({'name': 'filer'})<CR>
nnoremap <silent> <space>n   <Cmd>call ddu#start({'name': 'filer_left'})<CR>
nnoremap <silent> <space>z   <Cmd>call ddu#start({'name': 'filer_float'})<CR>
'''

#  ui
[[plugins]]
repo = 'Shougo/ddu-ui-ff'
on_source = 'ddu.vim'

[plugins.ftplugin]
ddu-ff = '''
nnoremap <buffer><silent> <CR>      <Cmd>call ddu#ui#ff#do_action('itemAction')<CR>
nnoremap <buffer><silent> <Space>   <Cmd>call ddu#ui#ff#do_action('toggleSelectItem')<CR>
nnoremap <buffer><silent> <C-l>     <Cmd>call ddu#ui#ff#do_action('refreshItems')<CR>
nnoremap <buffer><silent> v         <Cmd>call ddu#ui#ff#do_action('toggleSelectItem')<CR>
nnoremap <buffer><silent> e         <Cmd>call ddu#ui#ff#do_action('itemAction', {'name': 'edit'})<CR>
nnoremap <buffer><silent> dd        <Cmd>call ddu#ui#ff#do_action('itemAction', {'name': 'delete'})<CR>
nnoremap <buffer><silent> c         <Cmd>call ddu#ui#ff#do_action('itemAction', {'name': 'cd'})<CR>
nnoremap <buffer><silent> i         <Cmd>call ddu#ui#ff#do_action('openFilterWindow')<CR>
nnoremap <buffer><silent> a         <Cmd>call ddu#ui#ff#do_action('chooseAction')<CR>
nnoremap <buffer><silent> q         <Cmd>call ddu#ui#ff#do_action('quit')<CR>
nnoremap <buffer><silent> p         <Cmd>call ddu#ui#ff#do_action('preview')<CR>
'''

ddu-ff-filter = '''
inoremap <buffer><silent> <CR>  <Esc><Cmd>close<CR>
nnoremap <buffer><silent> <CR>  <Cmd>close<CR>
nnoremap <buffer><silent> q     <Cmd>close<CR>
'''

[[plugins]]
repo = 'Shougo/ddu-ui-filer'
on_source = 'ddu.vim'
[plugins.ftplugin]
ddu-filer = '''
nnoremap <buffer><expr> <CR>
  \ ddu#ui#filer#is_directory() ?
  \ "<Cmd>call ddu#ui#filer#do_action('itemAction', {'name': 'narrow'})<CR>" :
  \ "<Cmd>call ddu#ui#filer#do_action('itemAction', {'name': 'open'})<CR>"

nnoremap <buffer><expr> o
  \ ddu#ui#filer#is_directory() ?
  \ "<Cmd>call ddu#ui#filer#do_action('expandItem')<CR>" :
  \ "<Cmd>call ddu#ui#filer#do_action('itemAction', {'name': 'open'})<CR>"

nnoremap <buffer><expr> O
  \ ddu#ui#filer#is_directory() ?
  \ "<Cmd>call ddu#ui#filer#do_action('collapseItem')<CR>" :
  \ ""

nnoremap <buffer><expr> l
  \ ddu#ui#filer#is_directory() ?
  \ "<Cmd>call ddu#ui#filer#do_action('itemAction', {'name': 'narrow'})<CR>" : ""

nnoremap <buffer><silent> h               <Cmd>call ddu#ui#filer#do_action('itemAction', {'name': 'narrow', 'params': {'path': '..'}})<CR>
nnoremap <buffer><silent> ~               <Cmd>call ddu#ui#filer#do_action('itemAction', {'name': 'narrow', 'params': {'path': expand('~')}})<CR>

nnoremap <buffer><silent> <Space>         <Cmd>call ddu#ui#filer#do_action('toggleSelectItem')<CR>
nnoremap <buffer><silent> <2-LeftMouse>   <Cmd>call ddu#ui#filer#do_action('toggleSelectItem')<CR>
nnoremap <buffer><silent> K               <Cmd>call ddu#ui#filer#do_action('itemAction', {'name': 'newDirectory'})<CR>
nnoremap <buffer><silent> L               <Cmd>call ddu#ui#filer#do_action('itemAction', {'name': 'newFile'})<CR>
nnoremap <buffer><silent> s               <Cmd>call ddu#ui#filer#do_action('itemAction', {'name': 'loclist'})<CR>
nnoremap <buffer><silent> x               <Cmd>call ddu#ui#filer#do_action('itemAction', {'name': 'executeSystem'})<CR>
nnoremap <buffer><silent> dd              <Cmd>call ddu#ui#filer#do_action('itemAction', {'name': 'delete'})<CR>
nnoremap <buffer><silent> yy              <Cmd>call ddu#ui#filer#do_action('itemAction', {'name': 'yank'})<CR>
nnoremap <buffer><silent> Y               <Cmd>call ddu#ui#filer#do_action('itemAction', {'name': 'copy'})<CR>
nnoremap <buffer><silent> P               <Cmd>call ddu#ui#filer#do_action('itemAction', {'name': 'paste'})<CR>
nnoremap <buffer><silent> R               <Cmd>call ddu#ui#filer#do_action('itemAction', {'name': 'rename'})<CR>
nnoremap <buffer><silent> M               <Cmd>call ddu#ui#filer#do_action('itemAction', {'name': 'move'})<CR>
nnoremap <buffer><silent> q               <Cmd>call ddu#ui#filer#do_action('quit')<CR>
'''


#  source
[[plugins]]
repo = 'Shougo/ddu-source-file'
on_source = 'ddu.vim'
[[plugins]]
repo = 'Shougo/ddu-source-file_rec'
on_source = 'ddu.vim'
[[plugins]]
repo = 'Shougo/ddu-source-line'
on_source = 'ddu.vim'
[[plugins]]
repo = 'shun/ddu-source-buffer'
on_source = 'ddu.vim'
[[plugins]]
repo = 'Shougo/ddu-source-file_old'
on_source = 'ddu.vim'
[[plugins]]
repo = 'matsui54/ddu-source-command_history'
on_source = 'ddu.vim'


#  kind
[[plugins]]
repo = 'Shougo/ddu-kind-file'
on_source = 'ddu.vim'

#  matcher
[[plugins]]
repo = 'Shougo/ddu-filter-matcher_substring'
on_source = 'ddu.vim'

#  column
[[plugins]]
repo = 'Shougo/ddu-column-filename'
on_source = 'ddu.vim'
