#================================================
[[plugins]]
repo = 'Shougo/dein.vim'
#================================================

[[plugins]]
repo = 'kana/vim-operator-user'
[[plugins]]
repo = 'rhysd/vim-operator-surround'
[[plugins]]
repo = 'kana/vim-textobj-user'
hook_add = '''
" operator mappings
map        <silent>sa             <Plug>(operator-surround-append)
map        <silent>sd             <Plug>(operator-surround-delete)
map        <silent>sr             <Plug>(operator-surround-replace)
omap       ab                     <Plug>(textobj-multiblock-a)
omap       ib                     <Plug>(textobj-multiblock-i)
vmap       ab                     <Plug>(textobj-multiblock-a)
vmap       ib                     <Plug>(textobj-multiblock-i)

" if you use vim-textobj-multiblock
nmap <silent>sdd <Plug>(operator-surround-delete)<Plug>(textobj-multiblock-a)
nmap <silent>srr <Plug>(operator-surround-replace)<Plug>(textobj-multiblock-a)
'''

[[plugins]]
repo = 'kana/vim-textobj-syntax'
[[plugins]]
repo = 'thinca/vim-textobj-between'
[[plugins]]
repo = 'osyo-manga/vim-textobj-multiblock'
[[plugins]]
repo = 'kana/vim-textobj-entire'
hook_add = '''
let g:textobj_entire_no_default_key_mappings = 1
omap av <Plug>(textobj-entire-a)
omap iv <Plug>(textobj-entire-i)
xmap av <Plug>(textobj-entire-a)
xmap iv <Plug>(textobj-entire-i)
'''

[[plugins]]
repo = 'junegunn/vim-easy-align'
hook_add = '''
xmap gga :Tabular
xmap ga  <Plug>(EasyAlign)
'''


[[plugins]]
repo = 'https://github.com/fuenor/jpmoveword.vim'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'scrooloose/nerdcommenter'
hook_add = '''
let g:NERDSpaceDelims=1
let g:NERDDefaultAlign='left'
let g:NERDCustomDelimiters = {'vim': {'left': '"','right':''}}
let g:NERDCreateDefaultMappings=0
map <Leader>c<space> <plug>NERDCommenterToggle
'''

[[plugins]]
repo='t9md/vim-quickhl.git'
hook_add = '''
nmap <leader>m <Plug>(quickhl-manual-this)
xmap <leader>m <Plug>(quickhl-manual-this)
nmap <leader>M <Plug>(quickhl-manual-reset)
xmap <leader>M <Plug>(quickhl-manual-reset)
'''

[[plugins]]
repo = 'asvetliakov/vim-easymotion'
hook_add = '''
map <leader>e <Plug>(easymotion-prefix)
'''
