[[plugins]]
repo = 'https://github.com/itchyny/lightline.vim'
hook_add = '''
let g:lightline = {
  \ 'separator': { 'left': '', 'right': '' },
  \ }
'''

[[plugins]]
repo = 'morhetz/gruvbox'
hook_add = '''
colorscheme gruvbox
set termguicolors
let g:lightline = {
  \ 'colorscheme': 'gruvbox',
  \ }
'''
